variables:
  VERSION_ID: '1.0.$CI_PIPELINE_ID'

stages:
  - build
  
build:
  only:
    - master
    - develop
  image: vicarahq/electron-builder-windows
  stage: build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/build/*.*
  script:
    - sed "s/0.0.0/${VERSION_ID}/g" package.json > _package.json && mv _package.json package.json
    - npm install && npm run build